### PR TITLE
pep8 style

### PR DESCRIPTION
**Pull request by frostefjell**
Fixed pep8 errors/warnings 

https://www.python.org/dev/peps/pep-0008/

(Trying my first pull request! :smile:)

### CODE REVIEW

**Comment by frostefjell** [comment]
ops, wrong repo?

**Comment by babs** [comment]
why ?

**Comment by frostefjell** [comment]
I just thought it was fun to try to make a pull request. :smile:

**Comment by babs** [comment]
Hum okay :)

**Pull request closed without merging**
